# This workflow will build a Java project with Maven and bundle them as native app installers with jDeploy
# See https://www.jdeploy.com for more information.

name: jDeploy CI with Maven

# TODO: only deploy on pushes to develop branch
on: [ push ]
#on:
#  push:
#    branches: ['deploy']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Set Version
        run: |
          # set DM_VERSION to maven version (timestamp)
          echo "DM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          # update package.json with app version
          sed -i .bak "s/\"version\": \".*\"/\"version\": \"${{ env.DM_VERSION }}\"/g" package.json

      - name: Build App Installer Bundles
        uses: shannah/jdeploy@master
        with:
          github_token: ${{ github.token }}
